# Generated by Django 4.2.9 on 2024-01-07 20:09

from django.db import migrations, models
import store.validator


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/images', validators=[store.validator.validate_file_size]),
        ),
    ]
